controller:
 service:
   type: ClusterIP
   annotations:
    #  cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "ingress-nginx-80-neg-http"}}}'
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    #  cloud.google.com/load-balancer-type: Internal